import type { LucideIcon } from "lucide-react";
import {
  ArrowLeft,
  ArrowRight,
  Bell,
  BookOpen,
  Briefcase,
  Calendar,
  CirclePlus,
  Compass,
  CreditCard,
  Film,
  Frown,
  Heart,
  Image,
  Laugh,
  LayoutList,
  Loader2,
  MessageCircle,
  MessageSquare,
  MoreHorizontal,
  Palette,
  Play,
  Search,
  Send,
  Share2,
  Sparkles,
  Store,
  Tag,
  Trash2,
  User,
  UserPlus,
  Users,
  Video,
  Volume2,
  VolumeX,
  X,
} from "lucide-react";

/** Material icon names used in the app → Lucide (shadcn default icon set) */
export const ICON_MAP: Record<string, LucideIcon> = {
  progress_activity: Loader2,
  dynamic_feed: LayoutList,
  close: X,
  image: Image,
  sell: Tag,
  more_horiz: MoreHorizontal,
  chat_bubble: MessageCircle,
  share: Share2,
  send: Send,
  favorite: Heart,
  sentiment_very_satisfied: Laugh,
  sentiment_dissatisfied: Frown,
  auto_awesome: Sparkles,
  auto_stories: BookOpen,
  groups: Users,
  group: Users,
  event: Calendar,
  explore: Compass,
  movie: Film,
  storefront: Store,
  work: Briefcase,
  play_arrow: Play,
  videocam: Video,
  add_circle: CirclePlus,
  chat: MessageSquare,
  person: User,
  search: Search,
  notifications: Bell,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  person_add: UserPlus,
  delete: Trash2,
  volume_off: VolumeX,
  volume_up: Volume2,
  palette: Palette,
  payments: CreditCard,
  comment: MessageCircle,
};

export type IconName = keyof typeof ICON_MAP;
